"""Opus Summary Region/HQ mapping -- all three divisions.

THE MANUAL REFERENCE WORKBOOK (Xandra's) IS THE AUTHORITATIVE STRUCTURE
for all three divisions, per explicit instruction (2026-08-19): the same
165 (Region, HQ) blocks, in the same order and grouping, are used for
Xandra, Onyx, and Guardians alike -- it is NOT re-derived from Annual
Targets' own rollup-row conventions, and never will be (see the original
Xandra mapping session's reasoning, still true here).

What differs per division is entirely which of those 165 blocks actually
RESOLVE against that division's own Annual Targets sheet -- Onyx and
Guardians are real, much smaller divisions that simply don't operate in
every HQ Xandra does (verified 2026-08-19: Onyx's Annual Targets sheet has
no Andhra Pradesh/Bihar/Karnataka/Telangana rows at all; Guardians is
smaller still). A block whose annual_targets_keys is None for a given
division means exactly that -- no BM/target data exists for that HQ under
that division -- NOT a bug to silently paper over.

Resolution method, applied independently per division (never assumed to
transfer from one division to another):
  - Exact HQ-name match (case/whitespace-normalized).
  - Duplicate/near-duplicate Annual Targets rows sharing one HQ name are
    ALL kept in annual_targets_keys -- app.review_opus_service sums them,
    the rule verified against Xandra's real reference numbers.
  - Xandra additionally has a small, hand-verified set of literal spelling
    variants (transposed letters, alternate spelling) resolved by
    inspecting the real candidate row -- see XANDRA history. This is NOT
    reused for Onyx/Guardians: their own near-miss candidates turned out
    to be Annual Targets combining TWO separate reference HQs into one row
    (e.g. Onyx's 'LATUR/NANDED' covering both 'Latur Pool' and 'Nanded'),
    which cannot be split without guessing each one's share -- left
    unresolved rather than silently apportioned.

No of BM is deliberately NOT stored here -- it differs by division for the
same HQ (verified: Ahmedabad Pool is 6 BM under Xandra, 5 under Onyx, 3
under Guardians) and is computed fresh from each division's own Annual
Targets rows at generation time (app.review_opus_service._compute_hq_block),
summed across annual_targets_keys exactly like TARGET itself.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class OpusHqBlock:
    """One HQ's row-block in the Opus Summary, in the reference workbook's
    own order -- `region`/`hq` are exactly the display values the generated
    workbook reproduces, for every division alike. `annual_targets_keys` is
    the list of (REGION, HQ) rows in THIS DIVISION'S OWN Annual Targets
    sheet whose monthly targets (and BM counts) are summed to produce this
    block's data -- None means UNRESOLVED for this division: nothing about
    this block may be computed, only flagged."""

    region: str
    hq: str
    annual_targets_keys: tuple | None


XANDRA_OPUS_HQ_BLOCKS: tuple[OpusHqBlock, ...] = (
    OpusHqBlock(region='Andhra Pradesh', hq='Guntur', annual_targets_keys=(('ANDHRA PRADESH', 'GUNTUR'),)),
    OpusHqBlock(region='Andhra Pradesh', hq='Nellore', annual_targets_keys=(('ANDHRA PRADESH', 'NELLORE'),)),
    OpusHqBlock(region='Andhra Pradesh', hq='Rajahmundry', annual_targets_keys=(('ANDHRA PRADESH', 'RAJAHMUNDARY'),)),
    OpusHqBlock(region='Andhra Pradesh', hq='Srikakulam', annual_targets_keys=(('ANDHRA PRADESH', 'SRIKAKULAM'),)),
    OpusHqBlock(region='Andhra Pradesh', hq='Vijayawada Pool', annual_targets_keys=(('ANDHRA PRADESH', 'VIJAYAWADA POOL'),)),
    OpusHqBlock(region='Andhra Pradesh', hq='Visakhapatnam', annual_targets_keys=(('ANDHRA PRADESH', 'VISAKHAPATNAM'),)),
    OpusHqBlock(region='Bihar', hq='Araria', annual_targets_keys=(('BIHAR', 'ARARIA'),)),
    OpusHqBlock(region='Bihar', hq='Begusarai', annual_targets_keys=(('BIHAR', 'BEGUSARAI'),)),
    OpusHqBlock(region='Bihar', hq='Bhagalpur', annual_targets_keys=(('BIHAR', 'BHAGALPUR'),)),
    OpusHqBlock(region='Bihar', hq='Chapra', annual_targets_keys=(('BIHAR', 'CHHAPRA'),)),
    OpusHqBlock(region='Bihar', hq='Darbhanga Pool', annual_targets_keys=(('BIHAR', 'DARBHANGA POOL'),)),
    OpusHqBlock(region='Bihar', hq='Dhanbad', annual_targets_keys=(('BIHAR', 'DHANBAD'),)),
    OpusHqBlock(region='Bihar', hq='Jamshedpur', annual_targets_keys=(('BIHAR', 'JAMSHEDPUR'),)),
    OpusHqBlock(region='Bihar', hq='Jamui', annual_targets_keys=(('BIHAR', 'JAMUI'),)),
    OpusHqBlock(region='Bihar', hq='Katihar', annual_targets_keys=(('BIHAR', 'KATIHAR'),)),
    OpusHqBlock(region='Bihar', hq='Kishanganj', annual_targets_keys=(('BIHAR', 'KISHANGANJ'),)),
    OpusHqBlock(region='Bihar', hq='Muzaffarpur Pool', annual_targets_keys=(('BIHAR', 'MUZAFFARPUR POOL'),)),
    OpusHqBlock(region='Bihar', hq='Patna Pool', annual_targets_keys=(('BIHAR', 'PATNA POOL'),)),
    OpusHqBlock(region='Bihar', hq='Purnia', annual_targets_keys=(('BIHAR', 'PURNEA'),)),
    OpusHqBlock(region='Bihar', hq='Ranchi', annual_targets_keys=(('BIHAR', 'RANCHI'),)),
    OpusHqBlock(region='Bihar', hq='Samastipur', annual_targets_keys=(('BIHAR', 'SAMASTIPUR'),)),
    OpusHqBlock(region='Bihar', hq='Sitamarhi', annual_targets_keys=(('BIHAR', 'SITAMARHI'),)),
    OpusHqBlock(region='Delhi NCR', hq='Agra Pool', annual_targets_keys=(('DELHI-NCR', 'AGRA POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='Aligarh', annual_targets_keys=(('DELHI-NCR', 'ALIGARH'),)),
    OpusHqBlock(region='Delhi NCR', hq='DELHI POOL', annual_targets_keys=(('DELHI-NCR', 'DELHI POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='SOUTH DELHI POOL', annual_targets_keys=(('DELHI-NCR', 'SOUTH DELHI POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='WEST DELHI POOL', annual_targets_keys=(('DELHI-NCR', 'WEST DELHI POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='Ghaziabad Pool', annual_targets_keys=(('DELHI-NCR', 'GHAZIABAD POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='Jhansi', annual_targets_keys=(('DELHI-NCR', 'JHANSI'),)),
    OpusHqBlock(region='Delhi NCR', hq='Meerut Pool', annual_targets_keys=(('DELHI-NCR', 'MEERUT POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='Noida', annual_targets_keys=(('DELHI-NCR', 'NOIDA'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Ahmedabad Pool', annual_targets_keys=(('GUJARAT-AH', 'AHMEDABAD POOL'), ('GUJARAT-AH', 'AHMEDABAD POOL'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Bhavnagar', annual_targets_keys=(('GUJARAT-AH', 'BHAVNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Bhuj', annual_targets_keys=(('GUJARAT-AH', 'BHUJ'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Himmatnagar', annual_targets_keys=(('GUJARAT-AH', 'HIMMATNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Jamnagar', annual_targets_keys=(('GUJARAT-AH', 'JAMNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Mehsana', annual_targets_keys=(('GUJARAT-AH', 'MEHSANA'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Palanpur', annual_targets_keys=(('GUJARAT-AH', 'PALANPUR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Rajkot Pool', annual_targets_keys=(('GUJARAT-AH', 'RAJKOT POOL'),)),
    OpusHqBlock(region='Gujarat - SRT', hq='Baroda Pool', annual_targets_keys=(('GUJARAT-ST', 'BARODA POOL'),)),
    OpusHqBlock(region='Gujarat - SRT', hq='Anand/Nadiad Pool', annual_targets_keys=(('GUJARAT-ST', 'ANAND/NADIAD POOL'),)),
    OpusHqBlock(region='Gujarat - SRT', hq='Navsari/Valsad', annual_targets_keys=(('GUJARAT-ST', 'NAVSARI/VALSAD'),)),
    OpusHqBlock(region='Gujarat - SRT', hq='Surat Pool', annual_targets_keys=(('GUJARAT-ST', 'SURAT POOL'),)),
    OpusHqBlock(region='Karnataka - BNG', hq='Bangalore Pool', annual_targets_keys=(('KARNATAKA', 'BANGALORE POOL'), ('KARNATAKA', 'BANGALORE POOL'), ('KARNATAKA', 'BANGALORE POOL'),)),
    OpusHqBlock(region='Karnataka - BNG', hq='Mysore', annual_targets_keys=(('KARNATAKA', 'MYSORE'),)),
    OpusHqBlock(region='Kerala', hq='Alleppey', annual_targets_keys=(('KERALA', 'ALLEPPEY'),)),
    OpusHqBlock(region='Kerala', hq='Calicut Pool', annual_targets_keys=(('KERALA', 'CALICUT POOL'),)),
    OpusHqBlock(region='Kerala', hq='Cochin Pool', annual_targets_keys=(('KERALA', 'COCHIN POOL'),)),
    OpusHqBlock(region='Kerala', hq='Kannur', annual_targets_keys=(('KERALA', 'KANNUR'),)),
    OpusHqBlock(region='Kerala', hq='Kasaragod', annual_targets_keys=(('KERALA', 'KASARAGOD'),)),
    OpusHqBlock(region='Kerala', hq='Kollam', annual_targets_keys=(('KERALA', 'KOLLAM'),)),
    OpusHqBlock(region='Kerala', hq='Kottayam', annual_targets_keys=(('KERALA', 'KOTTAYAM'),)),
    OpusHqBlock(region='Kerala', hq='Palakkad', annual_targets_keys=(('KERALA', 'PALAKKAD'),)),
    OpusHqBlock(region='Kerala', hq='Pathanamthitta', annual_targets_keys=(('KERALA', 'PATHANAMTHITTA'),)),
    OpusHqBlock(region='Kerala', hq='Perinthalmanna', annual_targets_keys=(('KERALA', 'PERINTHALMANNA'),)),
    OpusHqBlock(region='Kerala', hq='Trichur Pool', annual_targets_keys=(('KERALA', 'TRICHUR POOL'),)),
    OpusHqBlock(region='Kerala', hq='Trivandrum', annual_targets_keys=(('KERALA', 'TRIVANDRUM'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Gadhinglaj', annual_targets_keys=(('MAHARASHTRA', 'GADHINGLAJ/KUDAL'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Kolhapur Pool', annual_targets_keys=(('MAHARASHTRA', 'KOLHAPUR POOL'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Latur Pool', annual_targets_keys=(('MAHARASHTRA', 'LATUR POOL'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Nanded', annual_targets_keys=(('MAHARASHTRA', 'NANDED'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='PCMC Pool', annual_targets_keys=(('MAHARASHTRA', 'PCMC POOL'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Pune Pool', annual_targets_keys=(('MAHARASHTRA', 'PUNE POOL'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Sangli', annual_targets_keys=(('MAHARASHTRA', 'SANGLI'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Satara', annual_targets_keys=(('MAHARASHTRA', 'SATARA'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Solapur', annual_targets_keys=(('MAHARASHTRA', 'SOLAPUR'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Ahmednagar', annual_targets_keys=(('MAHARASHTRA', 'AHMEDNAGAR'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Akola', annual_targets_keys=(('MAHARASHTRA', 'AKOLA'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Amravati', annual_targets_keys=(('MAHARASHTRA', 'AMRAVATI'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Aurangabad Pool', annual_targets_keys=(('MAHARASHTRA', 'AURANGABAD POOL'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Dhule', annual_targets_keys=(('MAHARASHTRA', 'DHULE'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Jalgaon', annual_targets_keys=(('MAHARASHTRA', 'JALGAON'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Nagpur', annual_targets_keys=(('MAHARASHTRA', 'NAGPUR'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Nashik Pool', annual_targets_keys=(('MAHARASHTRA', 'NASHIK POOL'),)),
    OpusHqBlock(region='MPCG - CG', hq='Ambikapur', annual_targets_keys=(('CG', 'AMBIKAPUR'),)),
    OpusHqBlock(region='MPCG - CG', hq='Balaghat', annual_targets_keys=(('CG', 'BALAGHAT'),)),
    OpusHqBlock(region='MPCG - CG', hq='Bilaspur Pool', annual_targets_keys=(('CG', 'BILASPUR POOL'),)),
    OpusHqBlock(region='MPCG - CG', hq='Durg', annual_targets_keys=(('CG', 'DURG'),)),
    OpusHqBlock(region='MPCG - CG', hq='Jabalpur Pool', annual_targets_keys=(('CG', 'JABALPUR POOL'),)),
    OpusHqBlock(region='MPCG - CG', hq='Raigarh', annual_targets_keys=(('CG', 'RAIGARH'),)),
    OpusHqBlock(region='MPCG - CG', hq='Raipur Pool', annual_targets_keys=(('CG', 'RAIPUR POOL'),)),
    OpusHqBlock(region='MPCG - CG', hq='Rewa', annual_targets_keys=(('CG', 'REWA'),)),
    OpusHqBlock(region='MPCG - CG', hq='Satna', annual_targets_keys=(('CG', 'SATNA'),)),
    OpusHqBlock(region='MPCG - MP', hq='Bhopal Pool', annual_targets_keys=(('MP', 'BHOPAL POOL'),)),
    OpusHqBlock(region='MPCG - MP', hq='Guna', annual_targets_keys=(('MP', 'GUNA'),)),
    OpusHqBlock(region='MPCG - MP', hq='Gwalior Pool', annual_targets_keys=(('MP', 'GWALIOR POOL'),)),
    OpusHqBlock(region='MPCG - MP', hq='Indore Pool', annual_targets_keys=(('MP', 'INDORE POOL'),)),
    OpusHqBlock(region='MPCG - MP', hq='Khandwa', annual_targets_keys=(('MP', 'KHANDWA'),)),
    OpusHqBlock(region='MPCG - MP', hq='Sagar', annual_targets_keys=(('MP', 'SAGAR'),)),
    OpusHqBlock(region='MPCG - MP', hq='Ujjain/Ratlam', annual_targets_keys=(('MP', 'UJJAIN'),)),
    OpusHqBlock(region='Mumbai - 1', hq='Kalyan', annual_targets_keys=(('MUMBAI', 'KALYAN'),)),
    OpusHqBlock(region='Mumbai - 1', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Navi Mumbai', annual_targets_keys=(('MUMBAI', 'NAVI MUMBAI'),)),
    OpusHqBlock(region='Mumbai - 1', hq='Raigad', annual_targets_keys=(('MUMBAI', 'RAIGAD'),)),
    OpusHqBlock(region='Mumbai - 1', hq='Thane Pool', annual_targets_keys=(('MUMBAI', 'THANE POOL'),)),
    OpusHqBlock(region='Mumbai - 2', hq='Mira Road Pool', annual_targets_keys=(('MUMBAI', 'MIRA ROAD POOL'),)),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai', annual_targets_keys=(('MUMBAI', 'MUMBAI'),)),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Amritsar', annual_targets_keys=(('PUNJAB', 'AMRITSAR'),)),
    OpusHqBlock(region='Punjab', hq='Bathinda', annual_targets_keys=(('PUNJAB', 'BHATINDA'),)),
    OpusHqBlock(region='Punjab', hq='Chandigarh', annual_targets_keys=(('PUNJAB', 'CHANDIGARH'),)),
    OpusHqBlock(region='Punjab', hq='Jalandhar', annual_targets_keys=(('PUNJAB', 'JALANDHAR'),)),
    OpusHqBlock(region='Punjab', hq='Jammu Pool', annual_targets_keys=(('PUNJAB', 'JAMMU POOL'),)),
    OpusHqBlock(region='Punjab', hq='Ludhiana Pool', annual_targets_keys=(('PUNJAB', 'LUDHIANA POOL'),)),
    OpusHqBlock(region='Punjab', hq='Moga', annual_targets_keys=(('PUNJAB', 'MOGA'),)),
    OpusHqBlock(region='Punjab', hq='Mohali', annual_targets_keys=(('PUNJAB', 'MOHALI'),)),
    OpusHqBlock(region='Punjab', hq='Patiala', annual_targets_keys=(('PUNJAB', 'PATIALA'),)),
    OpusHqBlock(region='Punjab', hq='Sangrur', annual_targets_keys=(('PUNJAB', 'SANGRUR'),)),
    OpusHqBlock(region='Rajasthan', hq='Ajmer', annual_targets_keys=(('RAJASTHAN', 'AJMER'),)),
    OpusHqBlock(region='Rajasthan', hq='Alwar', annual_targets_keys=(('RAJASTHAN', 'ALWAR'),)),
    OpusHqBlock(region='Rajasthan', hq='Bhilwara', annual_targets_keys=(('RAJASTHAN', 'BHILWARA'),)),
    OpusHqBlock(region='Rajasthan', hq='Bikaner', annual_targets_keys=(('RAJASTHAN', 'BIKANER'),)),
    OpusHqBlock(region='Rajasthan', hq='Jaipur Pool', annual_targets_keys=(('RAJASTHAN', 'JAIPUR POOL'),)),
    OpusHqBlock(region='Rajasthan', hq='Jodhpur Pool', annual_targets_keys=(('RAJASTHAN', 'JODHPUR POOL'),)),
    OpusHqBlock(region='Rajasthan', hq='Kota Pool', annual_targets_keys=(('RAJASTHAN', 'KOTA POOL'),)),
    OpusHqBlock(region='Rajasthan', hq='Pali', annual_targets_keys=(('RAJASTHAN', 'PALI'),)),
    OpusHqBlock(region='Rajasthan', hq='Sikar', annual_targets_keys=(('RAJASTHAN', 'SIKAR'),)),
    OpusHqBlock(region='Rajasthan', hq='Sriganganagar', annual_targets_keys=(('RAJASTHAN', 'SRIGANGANAGAR'),)),
    OpusHqBlock(region='Rajasthan', hq='Udaipur', annual_targets_keys=(('RAJASTHAN', 'UDAIPUR'),)),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Chennai Pool', annual_targets_keys=(('TAMILNADU-CH', 'CHENNAI POOL'), ('TAMILNADU-CH', 'CHENNAI POOL'), ('TAMILNADU-CH', 'CHENNAI POOL'),)),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Pondicherry', annual_targets_keys=(('TAMILNADU-CH', 'PONDICHERRY'),)),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Vellore', annual_targets_keys=(('TAMILNADU-CH', 'VELLORE'),)),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Viluppuram', annual_targets_keys=(('TAMILNADU-CH', 'VILUPPURAM'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Coimbatore Pool', annual_targets_keys=(('TAMILNADU-COIM', 'COIMBATORE POOL'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Erode', annual_targets_keys=(('TAMILNADU-COIM', 'ERODE'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Kumbakonam', annual_targets_keys=(('TAMILNADU-COIM', 'KUMBAKONAM'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Madurai Pool', annual_targets_keys=(('TAMILNADU-COIM', 'MADURAI POOL'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Salem', annual_targets_keys=(('TAMILNADU-COIM', 'SALEM'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Thanjavur', annual_targets_keys=(('TAMILNADU-COIM', 'THANJAVUR'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Tirunelveli', annual_targets_keys=(('TAMILNADU-COIM', 'TIRUNELVELI'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Trichy Pool', annual_targets_keys=(('TAMILNADU-COIM', 'TRICHY POOL'),)),
    OpusHqBlock(region='Telangana', hq='Hyderabad Pool', annual_targets_keys=(('TELENGANA', 'HYDERABAD POOL'), ('TELENGANA', 'HYDERABAD POOL'), ('TELENGANA', 'HYDERABAD POOL'),)),
    OpusHqBlock(region='Telangana', hq='Karimnagar', annual_targets_keys=(('TELENGANA', 'KARIMNAGAR'),)),
    OpusHqBlock(region='Telangana', hq='Nizamabad', annual_targets_keys=(('TELENGANA', 'NIZAMABAD'),)),
    OpusHqBlock(region='Telangana', hq='Warangal', annual_targets_keys=(('TELENGANA', 'WARANGAL'),)),
    OpusHqBlock(region='UP East - G', hq='Akbarpur', annual_targets_keys=(('UP EAST-G', 'AKBARPUR'),)),
    OpusHqBlock(region='UP East - G', hq='Ayodhya', annual_targets_keys=(('UP EAST-G', 'AYODHYA'),)),
    OpusHqBlock(region='UP East - G', hq='Azamgarh', annual_targets_keys=(('UP EAST-G', 'AZAMGARH'),)),
    OpusHqBlock(region='UP East - G', hq='BAHRAICH', annual_targets_keys=(('UP EAST-G', 'BAHRAICH'),)),
    OpusHqBlock(region='UP East - G', hq='Ballia', annual_targets_keys=(('UP EAST-G', 'BALLIA'),)),
    OpusHqBlock(region='UP East - G', hq='Basti', annual_targets_keys=(('UP EAST-G', 'BASTI'),)),
    OpusHqBlock(region='UP East - G', hq='Deoria', annual_targets_keys=(('UP EAST-G', 'DEORIA'),)),
    OpusHqBlock(region='UP East - G', hq='Gonda', annual_targets_keys=(('UP EAST-G', 'GONDA'),)),
    OpusHqBlock(region='UP East - G', hq='Gorakhpur Pool', annual_targets_keys=(('UP EAST-G', 'GORAKHPUR POOL'),)),
    OpusHqBlock(region='UP East - G', hq='Mau', annual_targets_keys=(('UP EAST-G', 'MAU'),)),
    OpusHqBlock(region='UP East - G', hq='Siddharthnagar', annual_targets_keys=(('UP EAST-G', 'SIDDHARTHNAGAR'),)),
    OpusHqBlock(region='UP East - G', hq='Sultanpur', annual_targets_keys=(('UP EAST-G', 'SULTANPUR'),)),
    OpusHqBlock(region='UP East - L', hq='Hardoi', annual_targets_keys=(('UP EAST-L', 'HARDOI'),)),
    OpusHqBlock(region='UP East - L', hq='Jaunpur', annual_targets_keys=(('UP EAST-L', 'JAUNPUR'),)),
    OpusHqBlock(region='UP East - L', hq='Kanpur Pool', annual_targets_keys=(('UP EAST-L', 'KANPUR POOL'),)),
    OpusHqBlock(region='UP East - L', hq='Lucknow Pool', annual_targets_keys=(('UP EAST-L', 'LUCKNOW POOL'),)),
    OpusHqBlock(region='UP East - L', hq='Prayagraj Pool', annual_targets_keys=(('UP EAST-L', 'PRAYAGRAJ POOL'),)),
    OpusHqBlock(region='UP East - L', hq='Varanasi Pool', annual_targets_keys=(('UP EAST-L', 'VARANASI POOL'),)),
    OpusHqBlock(region='UP West', hq='Bareilly Pool', annual_targets_keys=(('UP WEST', 'BAREILLY POOL'),)),
    OpusHqBlock(region='UP West', hq='Dehradun/Haridwar/Rishikesh', annual_targets_keys=(('UP WEST', 'RISHIKESH/HARIDWAR/DEHRADUN'),)),
    OpusHqBlock(region='UP West', hq='Haldwani', annual_targets_keys=(('UP WEST', 'HALDWANI'),)),
    OpusHqBlock(region='UP West', hq='Kashipur', annual_targets_keys=(('UP WEST', 'KASHIPUR'),)),
    OpusHqBlock(region='UP West', hq='Lakhimpur', annual_targets_keys=(('UP WEST', 'LAKHIMPUR'),)),
    OpusHqBlock(region='UP West', hq='Moradabad', annual_targets_keys=(('UP WEST', 'MORADABAD'),)),
    OpusHqBlock(region='UP West', hq='Muzaffarnagar', annual_targets_keys=(('UP WEST', 'MUZAFFARNAGAR'),)),
    OpusHqBlock(region='UP West', hq='Pilibhit', annual_targets_keys=(('UP WEST', 'PILIBHIT'),)),
    OpusHqBlock(region='UP West', hq='Rudrapur', annual_targets_keys=(('UP WEST', 'RUDRAPUR'),)),
    OpusHqBlock(region='UP West', hq='Saharanpur', annual_targets_keys=(('UP WEST', 'SAHARANPUR'),)),
)

assert len(XANDRA_OPUS_HQ_BLOCKS) == 165

ONYX_OPUS_HQ_BLOCKS: tuple[OpusHqBlock, ...] = (
    OpusHqBlock(region='Andhra Pradesh', hq='Guntur', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Nellore', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Rajahmundry', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Srikakulam', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Vijayawada Pool', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Visakhapatnam', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Araria', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Begusarai', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Bhagalpur', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Chapra', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Darbhanga Pool', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Dhanbad', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Jamshedpur', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Jamui', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Katihar', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Kishanganj', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Muzaffarpur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Patna Pool', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Purnia', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Ranchi', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Samastipur', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Sitamarhi', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='Agra Pool', annual_targets_keys=(('DELHI-NCR', 'AGRA POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='Aligarh', annual_targets_keys=(('DELHI-NCR', 'ALIGARH'),)),
    OpusHqBlock(region='Delhi NCR', hq='DELHI POOL', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='SOUTH DELHI POOL', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='WEST DELHI POOL', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='Ghaziabad Pool', annual_targets_keys=(('DELHI-NCR', 'GHAZIABAD POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='Jhansi', annual_targets_keys=(('DELHI-NCR', 'JHANSI'),)),
    OpusHqBlock(region='Delhi NCR', hq='Meerut Pool', annual_targets_keys=(('DELHI-NCR', 'MEERUT POOL'),)),
    OpusHqBlock(region='Delhi NCR', hq='Noida', annual_targets_keys=(('DELHI-NCR', 'NOIDA'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Ahmedabad Pool', annual_targets_keys=(('GUJARAT-AH', 'AHMEDABAD POOL'), ('GUJARAT-AH', 'AHMEDABAD POOL'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Bhavnagar', annual_targets_keys=(('GUJARAT-AH', 'BHAVNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Bhuj', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - AHM', hq='Himmatnagar', annual_targets_keys=(('GUJARAT-AH', 'HIMMATNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Jamnagar', annual_targets_keys=(('GUJARAT-AH', 'JAMNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Mehsana', annual_targets_keys=(('GUJARAT-AH', 'MEHSANA'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Palanpur', annual_targets_keys=(('GUJARAT-AH', 'PALANPUR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Rajkot Pool', annual_targets_keys=(('GUJARAT-AH', 'RAJKOT POOL'),)),
    OpusHqBlock(region='Gujarat - SRT', hq='Baroda Pool', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - SRT', hq='Anand/Nadiad Pool', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - SRT', hq='Navsari/Valsad', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - SRT', hq='Surat Pool', annual_targets_keys=None),
    OpusHqBlock(region='Karnataka - BNG', hq='Bangalore Pool', annual_targets_keys=None),
    OpusHqBlock(region='Karnataka - BNG', hq='Mysore', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Alleppey', annual_targets_keys=(('KERALA', 'ALLEPPEY'),)),
    OpusHqBlock(region='Kerala', hq='Calicut Pool', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Cochin Pool', annual_targets_keys=(('KERALA', 'COCHIN POOL'),)),
    OpusHqBlock(region='Kerala', hq='Kannur', annual_targets_keys=(('KERALA', 'KANNUR'),)),
    OpusHqBlock(region='Kerala', hq='Kasaragod', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Kollam', annual_targets_keys=(('KERALA', 'KOLLAM'),)),
    OpusHqBlock(region='Kerala', hq='Kottayam', annual_targets_keys=(('KERALA', 'KOTTAYAM'),)),
    OpusHqBlock(region='Kerala', hq='Palakkad', annual_targets_keys=(('KERALA', 'PALAKKAD'),)),
    OpusHqBlock(region='Kerala', hq='Pathanamthitta', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Perinthalmanna', annual_targets_keys=(('KERALA', 'PERINTHALMANNA'),)),
    OpusHqBlock(region='Kerala', hq='Trichur Pool', annual_targets_keys=(('KERALA', 'TRICHUR POOL'),)),
    OpusHqBlock(region='Kerala', hq='Trivandrum', annual_targets_keys=(('KERALA', 'TRIVANDRUM'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Gadhinglaj', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Kolhapur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Latur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Nanded', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='PCMC Pool', annual_targets_keys=(('MAHARASHTRA', 'PCMC POOL'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Pune Pool', annual_targets_keys=(('MAHARASHTRA', 'PUNE POOL'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Sangli', annual_targets_keys=(('MAHARASHTRA', 'SANGLI'),)),
    OpusHqBlock(region='Maharashtra - 1', hq='Satara', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Solapur', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Ahmednagar', annual_targets_keys=(('MAHARASHTRA', 'AHMEDNAGAR'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Akola', annual_targets_keys=(('MAHARASHTRA', 'AKOLA'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Amravati', annual_targets_keys=(('MAHARASHTRA', 'AMRAVATI'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Aurangabad Pool', annual_targets_keys=(('MAHARASHTRA', 'AURANGABAD POOL'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Dhule', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Jalgaon', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Nagpur', annual_targets_keys=(('MAHARASHTRA', 'NAGPUR'),)),
    OpusHqBlock(region='Maharashtra - 2', hq='Nashik Pool', annual_targets_keys=(('MAHARASHTRA', 'NASHIK POOL'),)),
    OpusHqBlock(region='MPCG - CG', hq='Ambikapur', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Balaghat', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Bilaspur Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Durg', annual_targets_keys=(('CG', 'DURG'),)),
    OpusHqBlock(region='MPCG - CG', hq='Jabalpur Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Raigarh', annual_targets_keys=(('CG', 'RAIGARH'),)),
    OpusHqBlock(region='MPCG - CG', hq='Raipur Pool', annual_targets_keys=(('CG', 'RAIPUR POOL'),)),
    OpusHqBlock(region='MPCG - CG', hq='Rewa', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Satna', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Bhopal Pool', annual_targets_keys=(('MP', 'BHOPAL POOL'),)),
    OpusHqBlock(region='MPCG - MP', hq='Guna', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Gwalior Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Indore Pool', annual_targets_keys=(('MP', 'INDORE POOL'),)),
    OpusHqBlock(region='MPCG - MP', hq='Khandwa', annual_targets_keys=(('MP', 'KHANDWA'),)),
    OpusHqBlock(region='MPCG - MP', hq='Sagar', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Ujjain/Ratlam', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Kalyan', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Navi Mumbai', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Raigad', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Thane Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mira Road Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Amritsar', annual_targets_keys=(('PUNJAB', 'AMRITSAR'),)),
    OpusHqBlock(region='Punjab', hq='Bathinda', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Chandigarh', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Jalandhar', annual_targets_keys=(('PUNJAB', 'JALANDHAR'),)),
    OpusHqBlock(region='Punjab', hq='Jammu Pool', annual_targets_keys=(('PUNJAB', 'JAMMU POOL'),)),
    OpusHqBlock(region='Punjab', hq='Ludhiana Pool', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Moga', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Mohali', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Patiala', annual_targets_keys=(('PUNJAB', 'PATIALA'),)),
    OpusHqBlock(region='Punjab', hq='Sangrur', annual_targets_keys=(('PUNJAB', 'SANGRUR'),)),
    OpusHqBlock(region='Rajasthan', hq='Ajmer', annual_targets_keys=(('RAJASTHAN', 'AJMER'),)),
    OpusHqBlock(region='Rajasthan', hq='Alwar', annual_targets_keys=(('RAJASTHAN', 'ALWAR'),)),
    OpusHqBlock(region='Rajasthan', hq='Bhilwara', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Bikaner', annual_targets_keys=(('RAJASTHAN', 'BIKANER'),)),
    OpusHqBlock(region='Rajasthan', hq='Jaipur Pool', annual_targets_keys=(('RAJASTHAN', 'JAIPUR POOL'),)),
    OpusHqBlock(region='Rajasthan', hq='Jodhpur Pool', annual_targets_keys=(('RAJASTHAN', 'JODHPUR POOL'),)),
    OpusHqBlock(region='Rajasthan', hq='Kota Pool', annual_targets_keys=(('RAJASTHAN', 'KOTA POOL'),)),
    OpusHqBlock(region='Rajasthan', hq='Pali', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Sikar', annual_targets_keys=(('RAJASTHAN', 'SIKAR'),)),
    OpusHqBlock(region='Rajasthan', hq='Sriganganagar', annual_targets_keys=(('RAJASTHAN', 'SRIGANGANAGAR'),)),
    OpusHqBlock(region='Rajasthan', hq='Udaipur', annual_targets_keys=(('RAJASTHAN', 'UDAIPUR'),)),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Chennai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Pondicherry', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Vellore', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Viluppuram', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Coimbatore Pool', annual_targets_keys=(('TAMILNADU-COIM', 'COIMBATORE POOL'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Erode', annual_targets_keys=(('TAMILNADU-COIM', 'ERODE'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Kumbakonam', annual_targets_keys=(('TAMILNADU-COIM', 'KUMBAKONAM'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Madurai Pool', annual_targets_keys=(('TAMILNADU-COIM', 'MADURAI POOL'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Salem', annual_targets_keys=(('TAMILNADU-COIM', 'SALEM'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Thanjavur', annual_targets_keys=(('TAMILNADU-COIM', 'THANJAVUR'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Tirunelveli', annual_targets_keys=(('TAMILNADU-COIM', 'TIRUNELVELI'),)),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Trichy Pool', annual_targets_keys=(('TAMILNADU-COIM', 'TRICHY POOL'),)),
    OpusHqBlock(region='Telangana', hq='Hyderabad Pool', annual_targets_keys=None),
    OpusHqBlock(region='Telangana', hq='Karimnagar', annual_targets_keys=None),
    OpusHqBlock(region='Telangana', hq='Nizamabad', annual_targets_keys=None),
    OpusHqBlock(region='Telangana', hq='Warangal', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Akbarpur', annual_targets_keys=(('UP EAST-G', 'AKBARPUR'),)),
    OpusHqBlock(region='UP East - G', hq='Ayodhya', annual_targets_keys=(('UP EAST-G', 'AYODHYA'),)),
    OpusHqBlock(region='UP East - G', hq='Azamgarh', annual_targets_keys=(('UP EAST-G', 'AZAMGARH'),)),
    OpusHqBlock(region='UP East - G', hq='BAHRAICH', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Ballia', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Basti', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Deoria', annual_targets_keys=(('UP EAST-G', 'DEORIA'),)),
    OpusHqBlock(region='UP East - G', hq='Gonda', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Gorakhpur Pool', annual_targets_keys=(('UP EAST-G', 'GORAKHPUR POOL'),)),
    OpusHqBlock(region='UP East - G', hq='Mau', annual_targets_keys=(('UP EAST-G', 'MAU'),)),
    OpusHqBlock(region='UP East - G', hq='Siddharthnagar', annual_targets_keys=(('UP EAST-G', 'SIDDHARTHNAGAR'),)),
    OpusHqBlock(region='UP East - G', hq='Sultanpur', annual_targets_keys=None),
    OpusHqBlock(region='UP East - L', hq='Hardoi', annual_targets_keys=(('UP EAST-L', 'HARDOI'),)),
    OpusHqBlock(region='UP East - L', hq='Jaunpur', annual_targets_keys=(('UP EAST-G', 'JAUNPUR'),)),
    OpusHqBlock(region='UP East - L', hq='Kanpur Pool', annual_targets_keys=None),
    OpusHqBlock(region='UP East - L', hq='Lucknow Pool', annual_targets_keys=(('UP EAST-L', 'LUCKNOW POOL'),)),
    OpusHqBlock(region='UP East - L', hq='Prayagraj Pool', annual_targets_keys=(('UP EAST-G', 'PRAYAGRAJ POOL'),)),
    OpusHqBlock(region='UP East - L', hq='Varanasi Pool', annual_targets_keys=(('UP EAST-G', 'VARANASI POOL'),)),
    OpusHqBlock(region='UP West', hq='Bareilly Pool', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Dehradun/Haridwar/Rishikesh', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Haldwani', annual_targets_keys=(('UP WEST', 'HALDWANI'),)),
    OpusHqBlock(region='UP West', hq='Kashipur', annual_targets_keys=(('UP WEST', 'KASHIPUR'),)),
    OpusHqBlock(region='UP West', hq='Lakhimpur', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Moradabad', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Muzaffarnagar', annual_targets_keys=(('UP WEST', 'MUZAFFARNAGAR'),)),
    OpusHqBlock(region='UP West', hq='Pilibhit', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Rudrapur', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Saharanpur', annual_targets_keys=(('UP WEST', 'SAHARANPUR'),)),
)

assert len(ONYX_OPUS_HQ_BLOCKS) == 165

GUARDIANS_OPUS_HQ_BLOCKS: tuple[OpusHqBlock, ...] = (
    OpusHqBlock(region='Andhra Pradesh', hq='Guntur', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Nellore', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Rajahmundry', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Srikakulam', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Vijayawada Pool', annual_targets_keys=None),
    OpusHqBlock(region='Andhra Pradesh', hq='Visakhapatnam', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Araria', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Begusarai', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Bhagalpur', annual_targets_keys=(('BIHAR', 'BHAGALPUR'),)),
    OpusHqBlock(region='Bihar', hq='Chapra', annual_targets_keys=(('BIHAR', 'CHAPRA'),)),
    OpusHqBlock(region='Bihar', hq='Darbhanga Pool', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Dhanbad', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Jamshedpur', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Jamui', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Katihar', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Kishanganj', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Muzaffarpur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Patna Pool', annual_targets_keys=(('BIHAR', 'PATNA POOL'),)),
    OpusHqBlock(region='Bihar', hq='Purnia', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Ranchi', annual_targets_keys=None),
    OpusHqBlock(region='Bihar', hq='Samastipur', annual_targets_keys=(('BIHAR', 'SAMASTIPUR'),)),
    OpusHqBlock(region='Bihar', hq='Sitamarhi', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='Agra Pool', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='Aligarh', annual_targets_keys=(('UP WEST', 'ALIGARH'),)),
    OpusHqBlock(region='Delhi NCR', hq='DELHI POOL', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='SOUTH DELHI POOL', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='WEST DELHI POOL', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='Ghaziabad Pool', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='Jhansi', annual_targets_keys=(('UP WEST', 'JHANSI'),)),
    OpusHqBlock(region='Delhi NCR', hq='Meerut Pool', annual_targets_keys=None),
    OpusHqBlock(region='Delhi NCR', hq='Noida', annual_targets_keys=(('UP WEST', 'NOIDA'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Ahmedabad Pool', annual_targets_keys=(('GUJARAT-AH', 'AHMEDABAD POOL'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Bhavnagar', annual_targets_keys=(('GUJARAT-AH', 'BHAVNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Bhuj', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - AHM', hq='Himmatnagar', annual_targets_keys=(('GUJARAT-AH', 'HIMMATNAGAR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Jamnagar', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - AHM', hq='Mehsana', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - AHM', hq='Palanpur', annual_targets_keys=(('GUJARAT-AH', 'PALANPUR'),)),
    OpusHqBlock(region='Gujarat - AHM', hq='Rajkot Pool', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - SRT', hq='Baroda Pool', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - SRT', hq='Anand/Nadiad Pool', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - SRT', hq='Navsari/Valsad', annual_targets_keys=None),
    OpusHqBlock(region='Gujarat - SRT', hq='Surat Pool', annual_targets_keys=(('GUJARAT-ST', 'SURAT POOL'),)),
    OpusHqBlock(region='Karnataka - BNG', hq='Bangalore Pool', annual_targets_keys=None),
    OpusHqBlock(region='Karnataka - BNG', hq='Mysore', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Alleppey', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Calicut Pool', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Cochin Pool', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Kannur', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Kasaragod', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Kollam', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Kottayam', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Palakkad', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Pathanamthitta', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Perinthalmanna', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Trichur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Kerala', hq='Trivandrum', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Gadhinglaj', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Kolhapur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Latur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Nanded', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='PCMC Pool', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Pune Pool', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Sangli', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Satara', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 1', hq='Solapur', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Ahmednagar', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Akola', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Amravati', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Aurangabad Pool', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Dhule', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Jalgaon', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Nagpur', annual_targets_keys=None),
    OpusHqBlock(region='Maharashtra - 2', hq='Nashik Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Ambikapur', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Balaghat', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Bilaspur Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Durg', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Jabalpur Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Raigarh', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Raipur Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Rewa', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - CG', hq='Satna', annual_targets_keys=(('MPCG', 'SATNA'),)),
    OpusHqBlock(region='MPCG - MP', hq='Bhopal Pool', annual_targets_keys=(('MPCG', 'BHOPAL POOL'),)),
    OpusHqBlock(region='MPCG - MP', hq='Guna', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Gwalior Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Indore Pool', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Khandwa', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Sagar', annual_targets_keys=None),
    OpusHqBlock(region='MPCG - MP', hq='Ujjain/Ratlam', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Kalyan', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Navi Mumbai', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Raigad', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 1', hq='Thane Pool', annual_targets_keys=(('MUMBAI', 'THANE POOL'),)),
    OpusHqBlock(region='Mumbai - 2', hq='Mira Road Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Mumbai - 2', hq='Mumbai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Amritsar', annual_targets_keys=(('PUNJAB', 'AMRITSAR'),)),
    OpusHqBlock(region='Punjab', hq='Bathinda', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Chandigarh', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Jalandhar', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Jammu Pool', annual_targets_keys=(('PUNJAB', 'JAMMU POOL'),)),
    OpusHqBlock(region='Punjab', hq='Ludhiana Pool', annual_targets_keys=(('PUNJAB', 'LUDHIANA POOL'),)),
    OpusHqBlock(region='Punjab', hq='Moga', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Mohali', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Patiala', annual_targets_keys=None),
    OpusHqBlock(region='Punjab', hq='Sangrur', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Ajmer', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Alwar', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Bhilwara', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Bikaner', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Jaipur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Jodhpur Pool', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Kota Pool', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Pali', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Sikar', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Sriganganagar', annual_targets_keys=None),
    OpusHqBlock(region='Rajasthan', hq='Udaipur', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Chennai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Pondicherry', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Vellore', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - CHN', hq='Viluppuram', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Coimbatore Pool', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Erode', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Kumbakonam', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Madurai Pool', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Salem', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Thanjavur', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Tirunelveli', annual_targets_keys=None),
    OpusHqBlock(region='Tamil Nadu - COIM', hq='Trichy Pool', annual_targets_keys=None),
    OpusHqBlock(region='Telangana', hq='Hyderabad Pool', annual_targets_keys=None),
    OpusHqBlock(region='Telangana', hq='Karimnagar', annual_targets_keys=None),
    OpusHqBlock(region='Telangana', hq='Nizamabad', annual_targets_keys=None),
    OpusHqBlock(region='Telangana', hq='Warangal', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Akbarpur', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Ayodhya', annual_targets_keys=(('UP-EAST', 'AYODHYA'),)),
    OpusHqBlock(region='UP East - G', hq='Azamgarh', annual_targets_keys=(('UP-EAST', 'AZAMGARH'),)),
    OpusHqBlock(region='UP East - G', hq='BAHRAICH', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Ballia', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Basti', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Deoria', annual_targets_keys=(('UP-EAST', 'DEORIA'),)),
    OpusHqBlock(region='UP East - G', hq='Gonda', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Gorakhpur Pool', annual_targets_keys=(('UP-EAST', 'GORAKHPUR POOL'),)),
    OpusHqBlock(region='UP East - G', hq='Mau', annual_targets_keys=(('UP-EAST', 'MAU'),)),
    OpusHqBlock(region='UP East - G', hq='Siddharthnagar', annual_targets_keys=None),
    OpusHqBlock(region='UP East - G', hq='Sultanpur', annual_targets_keys=None),
    OpusHqBlock(region='UP East - L', hq='Hardoi', annual_targets_keys=None),
    OpusHqBlock(region='UP East - L', hq='Jaunpur', annual_targets_keys=None),
    OpusHqBlock(region='UP East - L', hq='Kanpur Pool', annual_targets_keys=None),
    OpusHqBlock(region='UP East - L', hq='Lucknow Pool', annual_targets_keys=(('UP-EAST', 'LUCKNOW POOL'),)),
    OpusHqBlock(region='UP East - L', hq='Prayagraj Pool', annual_targets_keys=(('UP-EAST', 'PRAYAGRAJ POOL'),)),
    OpusHqBlock(region='UP East - L', hq='Varanasi Pool', annual_targets_keys=(('UP-EAST', 'VARANASI POOL'),)),
    OpusHqBlock(region='UP West', hq='Bareilly Pool', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Dehradun/Haridwar/Rishikesh', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Haldwani', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Kashipur', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Lakhimpur', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Moradabad', annual_targets_keys=(('UP WEST', 'MORADABAD'),)),
    OpusHqBlock(region='UP West', hq='Muzaffarnagar', annual_targets_keys=(('UP WEST', 'MUZAFFARNAGAR'),)),
    OpusHqBlock(region='UP West', hq='Pilibhit', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Rudrapur', annual_targets_keys=None),
    OpusHqBlock(region='UP West', hq='Saharanpur', annual_targets_keys=(('UP WEST', 'SAHARANPUR'),)),
)

assert len(GUARDIANS_OPUS_HQ_BLOCKS) == 165

# Every division that has been resolved so far -- adding one more is:
# build its OpusHqBlock tuple the same way (see resolve_division() in the
# generation script this file was produced from), add it here. No other
# file needs to change; app.review_opus_service reads this registry.
OPUS_HQ_BLOCKS_BY_DIVISION: dict = {
    "Xandra": XANDRA_OPUS_HQ_BLOCKS,
    "Onyx": ONYX_OPUS_HQ_BLOCKS,
    "Guardians": GUARDIANS_OPUS_HQ_BLOCKS,
}

