"""Findings page: review investigation findings generated by the rule engine.

Version 2.2: this single page now serves BOTH finding families via a TabBar
(see ui.components.TabBar) rather than a second page --
"Location-Based Findings" is the existing table (Same Location, fake calls,
any location rule), UNCHANGED except that it no longer shows HR findings;
"HR-Based Findings" is the Low Working Hours table over the HOURS_WORKED
rule's findings (rules/hours_worked.py), with room for a future Low Call
Count table beside it. Both tables share the one detail/review panel on the
right (a finding is a finding -- same finding_id, same status workflow), so
selecting a row in either tab reviews it through the same buttons.
"""

import threading

import customtkinter as ctk
from loguru import logger

from app.feature_flags_service import is_feature_enabled
from app.findings_service import get_all_findings, parse_hours_worked_message, set_status
from app.suppression_service import region_suppressed_finding_ids, suppressed_finding_ids_for_import
from app.findings_sync_service import push_finding_status
from app.session_state import get_active_import_id
from app.table_export_service import RowStyle, default_export_filename, export_rows_with_ui
from ui.components import Card, EmptyState, PrimaryButton, SecondaryButton, SectionHeader, StatusBadge, TabBar, styled_treeview
from ui.icons import get_icon
from ui.theme import Color, Font, Spacing

STATUS_BADGE_KIND = {"Open": "warning", "Reviewed": "success", "Ignored": "neutral"}

# Rules shown on the HR-Based Findings tab; everything else is Location-Based.
# Leave room here for a future "LOW_CALL_COUNT" without touching anything else.
HR_RULE_NAMES = {"HOURS_WORKED"}

# Notification outcome is a separate concept from the review `status` above
# (Open/Reviewed/Ignored) — this is what happened to the automatic email for
# this finding (see app/notification_service.py + app/hospital_service.py).
NOTIFICATION_STATUS_DISPLAY = {
    None: "Pending",
    "Sent": "Email Sent",
    "Hospital Suppressed": "Hospital Suppressed",
    "Suppressed - Region Rule": "Suppressed - Region Rule",
    "Failed": "Failed",
}
NOTIFICATION_BADGE_KIND = {
    "Pending": "neutral",
    "Email Sent": "success",
    "Hospital Suppressed": "warning",
    # Deliberately a different color from Hospital Suppressed ("warning") --
    # the Region Suppression Rule (app/region_suppression.py) is a distinct
    # business rule, not the same suppression mechanism, and must never read
    # as the same thing at a glance.
    "Suppressed - Region Rule": "primary",
    "Failed": "error",
}

COLUMNS = ("employee_name", "employee_code", "division", "visit_date", "rule_name", "notification_status", "status", "message")
HEADINGS = {
    "employee_name": "Employee",
    "employee_code": "Code",
    "division": "Division",
    "visit_date": "Date",
    "rule_name": "Rule",
    "notification_status": "Status",
    "status": "Review Status",
    "message": "Message",
}
WIDTHS = {
    "employee_name": 150,
    "employee_code": 80,
    "division": 100,
    "visit_date": 90,
    "rule_name": 120,
    "notification_status": 130,
    "status": 100,
    "message": 300,
}

# --- HR-Based (Low Working Hours) table -------------------------------------
HR_COLUMNS = ("employee", "visit_date", "first_call", "last_call", "hours_worked", "min_required", "hours_short", "status")
HR_HEADINGS = {
    "employee": "Employee",
    "visit_date": "Date",
    "first_call": "First Call",
    "last_call": "Last Call",
    "hours_worked": "Hours Worked",
    "min_required": "Minimum Required Hours",
    "hours_short": "Hours Short",
    "status": "Status",
}
HR_WIDTHS = {
    "employee": 180,
    "visit_date": 90,
    "first_call": 90,
    "last_call": 90,
    "hours_worked": 100,
    "min_required": 160,
    "hours_short": 90,
    "status": 100,
}

def _parse_hours_fields(message: str) -> dict:
    """Display strings for the Low Working Hours table, built from the shared
    app.findings_service parser (single source of the message format). Blanks
    if the message doesn't match."""
    parsed = parse_hours_worked_message(message)
    if not parsed:
        return {"first_call": "", "last_call": "", "hours_worked": "", "min_required": "", "hours_short": ""}
    return {
        "first_call": parsed["first_call"],
        "last_call": parsed["last_call"],
        "hours_worked": f"{parsed['hours_worked']:.1f}",
        "min_required": f"{parsed['minimum']:g}",
        "hours_short": f"{parsed['hours_short']:.1f}",
    }


# Fill colors for the exported-row equivalent of this page's own
# "suppressed"/"suppression_inconclusive"/"region_suppressed" Treeview
# tags (see _render_table) -- keyed by the same internal "_row_tag" value
# _render_table stashes into each exported row dict (never a real column,
# never printed -- see _findings_row_style below and
# app.table_export_service's row_style_fn contract).
_ROW_TAG_FILL = {
    "suppressed": Color.WARNING_SOFT,
    "suppression_inconclusive": Color.INFO_SOFT,
    "region_suppressed": Color.PRIMARY_SOFT,
}


def _findings_row_style(row: dict) -> RowStyle | None:
    fill = _ROW_TAG_FILL.get(row.get("_row_tag"))
    if fill is None:
        return None
    return RowStyle(fill_color=fill.lstrip("#"))


def _notification_status_display(finding) -> str:
    # Hospital Suppression is an experimental feature — when it's off for the
    # current mode, a finding must never read as "Hospital Suppressed"
    # anywhere (e.g. stale data from a prior run in another mode); show it as
    # Pending instead so the feature has zero footprint in User Mode.
    if finding.notification_status == "Hospital Suppressed" and not is_feature_enabled("hospital_suppression"):
        return "Pending"
    return NOTIFICATION_STATUS_DISPLAY.get(finding.notification_status, finding.notification_status)


def status_text_for_display(finding, region_suppressed_ids) -> str:
    """The Status text the Location-Based tab shows for a finding. A finding
    whose region is region-suppressed by the canonical live rule reads
    'Suppressed - Region Rule' regardless of whether the email pipeline has
    persisted that yet; everything else uses the persisted notification
    status. Pure (the region-suppressed id set is passed in) so it's testable
    without a Tk root."""
    if finding.finding_id in region_suppressed_ids:
        return "Suppressed - Region Rule"
    return _notification_status_display(finding)


def hr_status_text(finding, region_suppressed_ids) -> str:
    """The HR-Based Status column value: 'Suppressed - Region Rule' for a
    region-suppressed finding (canonical live rule -- the same determination
    the Location tab, Master, and email use), otherwise the review status.
    Pure (region-suppressed id set passed in) so it's testable without Tk."""
    if finding.finding_id in region_suppressed_ids:
        return "Suppressed - Region Rule"
    return finding.status


def findings_signature(findings) -> tuple:
    """A lightweight fingerprint of everything the Findings page renders per
    finding -- id plus the fields that drive the row/status/tint/exclusion.
    Two loads with the same signature render identically, so the page can skip
    a redundant table rebuild (which would reset the user's scroll position,
    selected row, and open suppression detail) on a no-op 15s refresh, while
    still rebuilding the instant any of these actually changes."""
    return tuple(
        (
            f.finding_id,
            f.notification_status,
            f.suppression_reason,
            f.status,
            f.employee_name,
            f.message,
        )
        for f in findings
    )


class FindingsPage(ctk.CTkFrame):
    """Tabbed findings (Location-Based / HR-Based) sharing one detail panel."""

    def __init__(self, master) -> None:
        super().__init__(master, fg_color=Color.SURFACE)

        self._findings_by_id: dict[int, object] = {}
        self._suppressed_ids: set = set()
        self._region_suppressed_ids: set = set()  # live region-suppressed (for Location-tab display)
        self._loaded_signature = None  # skip a redundant rebuild on an unchanged refresh
        self._current_display_rows: list[dict] = []
        self._sort_column = "visit_date"
        self._sort_reverse = True
        self._status_filter = "All"

        # HR-Based tab state
        self._hr_status_filter = "All"
        self._hr_display_rows: list[dict] = []

        self._build_widgets()

    def _build_widgets(self) -> None:
        outer = ctk.CTkFrame(self, fg_color="transparent")
        outer.pack(fill="both", expand=True, padx=Spacing.LG, pady=Spacing.LG)

        SectionHeader(
            outer, "Findings", "Review flagged employees from the investigation rule engine"
        ).pack(anchor="w", pady=(0, Spacing.LG))

        self.tabs = TabBar(
            outer, ["Location-Based Findings", "HR-Based Findings"], on_change=self._on_tab_changed
        )
        self.tabs.pack(fill="x", pady=(0, Spacing.MD))

        content_row = ctk.CTkFrame(outer, fg_color="transparent")
        content_row.pack(fill="both", expand=True)

        # Left: the two tab frames (only one packed at a time). Right: the one
        # shared detail/review panel, always visible for whichever row is
        # selected in whichever tab.
        self.tab_area = ctk.CTkFrame(content_row, fg_color="transparent")
        self.tab_area.pack(side="left", fill="both", expand=True, padx=(0, Spacing.MD))

        self.location_frame = ctk.CTkFrame(self.tab_area, fg_color="transparent")
        self.hr_frame = ctk.CTkFrame(self.tab_area, fg_color="transparent")
        self.location_frame.pack(fill="both", expand=True)  # default active tab

        self._build_location_table(self.location_frame)
        self._build_hr_table(self.hr_frame)

        # --- Shared detail panel ---------------------------------------------
        self.detail_card = Card(content_row, width=320)
        self.detail_card.pack(side="right", fill="y")
        self.detail_card.pack_propagate(False)

        # Scrollable: the suppression detail fields (hospital name, distance,
        # both sets of coordinates, reason) push a suppressed finding's
        # content past the fixed-height card, so a plain frame would just
        # clip everything below the fold.
        self.detail_container = ctk.CTkScrollableFrame(self.detail_card, fg_color="transparent")
        self.detail_container.pack(fill="both", expand=True, padx=Spacing.MD, pady=Spacing.MD)

        self._render_detail(None)

    def _build_location_table(self, parent) -> None:
        table_card = Card(parent)
        table_card.pack(fill="both", expand=True)

        table_body = ctk.CTkFrame(table_card, fg_color="transparent")
        table_body.pack(fill="both", expand=True, padx=Spacing.MD, pady=Spacing.MD)

        filter_row = ctk.CTkFrame(table_body, fg_color="transparent")
        filter_row.pack(fill="x", pady=(0, Spacing.SM))

        ctk.CTkLabel(filter_row, text="Filter:", font=Font.BODY, text_color=Color.TEXT_SECONDARY).pack(
            side="left", padx=(0, Spacing.SM)
        )
        self.status_menu = ctk.CTkOptionMenu(
            filter_row,
            values=["All", "Open", "Reviewed", "Ignored"],
            command=self._on_status_filter_changed,
            fg_color=Color.SURFACE,
            button_color=Color.PRIMARY,
            button_hover_color=Color.PRIMARY_HOVER,
            text_color=Color.TEXT_PRIMARY,
            width=130,
        )
        self.status_menu.pack(side="left", padx=(0, Spacing.MD))

        self.search_entry = ctk.CTkEntry(filter_row, placeholder_text="Search employee, code, or message…")
        self.search_entry.pack(side="left", fill="x", expand=True, padx=(0, Spacing.SM))
        self.search_entry.bind("<KeyRelease>", lambda event: self._render_table())

        self.export_button = PrimaryButton(
            filter_row,
            text="Export",
            image=get_icon("download", size=16, color=Color.TEXT_ON_PRIMARY),
            command=self._on_export_clicked,
        )
        self.export_button.pack(side="right")

        self.table_container = ctk.CTkFrame(table_body, fg_color="transparent")
        self.table_container.pack(fill="both", expand=True)

    def _build_hr_table(self, parent) -> None:
        table_card = Card(parent)
        table_card.pack(fill="both", expand=True)

        table_body = ctk.CTkFrame(table_card, fg_color="transparent")
        table_body.pack(fill="both", expand=True, padx=Spacing.MD, pady=Spacing.MD)

        ctk.CTkLabel(
            table_body, text="Low Working Hours", font=Font.SMALL_BOLD, text_color=Color.TEXT_SECONDARY, anchor="w"
        ).pack(anchor="w", pady=(0, Spacing.SM))

        filter_row = ctk.CTkFrame(table_body, fg_color="transparent")
        filter_row.pack(fill="x", pady=(0, Spacing.SM))

        ctk.CTkLabel(filter_row, text="Filter:", font=Font.BODY, text_color=Color.TEXT_SECONDARY).pack(
            side="left", padx=(0, Spacing.SM)
        )
        self.hr_status_menu = ctk.CTkOptionMenu(
            filter_row,
            values=["All", "Open", "Reviewed", "Ignored"],
            command=self._on_hr_status_filter_changed,
            fg_color=Color.SURFACE,
            button_color=Color.PRIMARY,
            button_hover_color=Color.PRIMARY_HOVER,
            text_color=Color.TEXT_PRIMARY,
            width=130,
        )
        self.hr_status_menu.pack(side="left", padx=(0, Spacing.MD))

        self.hr_search_entry = ctk.CTkEntry(filter_row, placeholder_text="Search employee or code…")
        self.hr_search_entry.pack(side="left", fill="x", expand=True, padx=(0, Spacing.SM))
        self.hr_search_entry.bind("<KeyRelease>", lambda event: self._render_hr_table())

        self.hr_export_button = PrimaryButton(
            filter_row,
            text="Export",
            image=get_icon("download", size=16, color=Color.TEXT_ON_PRIMARY),
            command=self._on_hr_export_clicked,
        )
        self.hr_export_button.pack(side="right")

        self.hr_table_container = ctk.CTkFrame(table_body, fg_color="transparent")
        self.hr_table_container.pack(fill="both", expand=True)

    def _on_tab_changed(self, tab_name: str) -> None:
        if tab_name == "Location-Based Findings":
            self.hr_frame.pack_forget()
            self.location_frame.pack(fill="both", expand=True)
        else:
            self.location_frame.pack_forget()
            self.hr_frame.pack(fill="both", expand=True)

    def on_show(self) -> None:
        """Called every time this page becomes visible — reload from the DB."""
        self._load_findings()

    def _load_findings(self, force: bool = False) -> None:
        import_id = get_active_import_id()
        findings = get_all_findings(import_id)

        # A 15s refresh that changed nothing findings-related (e.g. it only
        # touched config/workbook sync) must NOT rebuild the tables -- that
        # would reset the user's scroll, selection, and the suppression detail
        # they're viewing, making a correctly-displayed "Suppressed - Region
        # Rule" appear to flicker/reset. Rebuild only when something the page
        # actually renders has changed (or on an explicit force, e.g. after a
        # reviewer status click).
        signature = findings_signature(findings)
        if not force and signature == self._loaded_signature and self._findings_by_id:
            return
        self._loaded_signature = signature

        self._findings_by_id = {f.finding_id: f for f in findings}
        # Canonical region/hospital suppression (app.suppression_service),
        # computed once per load -- the HR-Based table drops these; the
        # Location tab still shows them (audit view).
        self._suppressed_ids = suppressed_finding_ids_for_import(findings, import_id)
        # Live region-suppression for the Location tab's status/tint -- the
        # canonical rule, not the persisted notification_status.
        self._region_suppressed_ids = region_suppressed_finding_ids(findings, import_id)
        hr_total = sum(1 for f in findings if f.rule_name in HR_RULE_NAMES)
        hr_suppressed = sum(1 for f in findings if f.rule_name in HR_RULE_NAMES and f.finding_id in self._suppressed_ids)
        logger.info(
            f"Findings page load: import={import_id} findings={len(findings)} "
            f"suppressed={len(self._suppressed_ids)} (HR {hr_suppressed}/{hr_total} suppressed)"
        )
        self._render_table()
        self._render_hr_table()

    # --- Location-Based tab ------------------------------------------------

    def _on_status_filter_changed(self, value: str) -> None:
        self._status_filter = value
        self._render_table()

    def _sort_key(self, finding):
        value = getattr(finding, self._sort_column)
        return (value is None, value)

    def _on_heading_clicked(self, column: str) -> None:
        if self._sort_column == column:
            self._sort_reverse = not self._sort_reverse
        else:
            self._sort_column = column
            self._sort_reverse = False
        self._render_table()

    def _on_export_clicked(self) -> None:
        """Exports `self._current_display_rows` -- the exact list
        `_render_table()` just used to populate the Treeview (built from
        the same per-finding dict the Treeview's own `values=` tuple
        reads, so there is only one place the displayed values are
        computed, never two that could drift apart)."""
        suffix = "" if self._status_filter == "All" else self._status_filter
        export_rows_with_ui(
            self,
            rows=self._current_display_rows,
            columns=COLUMNS,
            headings=HEADINGS,
            suggested_filename=default_export_filename("Findings", suffix=suffix),
            sheet_title="Findings",
            row_style_fn=_findings_row_style,
        )

    def _display_status(self, finding) -> str:
        return status_text_for_display(finding, self._region_suppressed_ids)

    def _render_table(self) -> None:
        for widget in self.table_container.winfo_children():
            widget.destroy()
        self._current_display_rows = []

        query = self.search_entry.get().strip().lower()
        # Location-Based tab: every finding that isn't an HR rule.
        findings = [f for f in self._findings_by_id.values() if f.rule_name not in HR_RULE_NAMES]

        if self._status_filter != "All":
            findings = [f for f in findings if f.status == self._status_filter]

        if query:
            findings = [
                f
                for f in findings
                if query in f.employee_name.lower()
                or query in f.employee_code.lower()
                or query in f.message.lower()
            ]

        findings.sort(key=self._sort_key, reverse=self._sort_reverse)

        if not findings:
            message = (
                "No active session file — import a workbook on the Operations page."
                if get_active_import_id() is None
                else "No findings match the current filter."
            )
            EmptyState(self.table_container, message).pack(fill="both", expand=True)
            return

        # height=14 (a modest requested row count) so the table fits a smaller
        # or lower-resolution screen without pushing its own bottom (and
        # horizontal scrollbar) off-screen; it still grows to fill a larger
        # window via fill/expand below, and scrolls when there are more rows.
        tree = styled_treeview(self.table_container, COLUMNS, HEADINGS, WIDTHS, height=14)
        for col in COLUMNS:
            tree.heading(col, text=HEADINGS[col], command=lambda c=col: self._on_heading_clicked(c))

        # Suppressed findings never received an email — highlight them so
        # they're easy to spot and audit at a glance, without having to
        # read the Status column text on every row. A different tint marks
        # findings whose hospital check couldn't be completed (lookup
        # failure or circuit-breaker skip) — their email still went out,
        # but the suppression decision itself is unverified and may need a
        # manual look, so it must never look like the same "checked and
        # clear" row as everyone else. Region-suppressed rows get their own
        # tint too, distinct from both -- it's a different business rule
        # (app/region_suppression.py), always on regardless of the
        # Hospital Suppression feature flag.
        tree.tag_configure("suppressed", background=Color.WARNING_SOFT)
        tree.tag_configure("suppression_inconclusive", background=Color.INFO_SOFT)
        tree.tag_configure("region_suppressed", background=Color.PRIMARY_SOFT)

        hospital_enabled = is_feature_enabled("hospital_suppression")
        for finding in findings:
            # Region suppression is decided by the canonical LIVE rule (the
            # employee/date region, app.region_suppression.is_region_suppressed),
            # NOT by whether the email pipeline has stamped notification_status
            # yet -- so a region-suppressed finding shows "Suppressed - Region
            # Rule" + tint immediately, matching Master/HR/email. Hospital
            # suppression still comes from the persisted status (it needs the
            # geocoding lookup that only runs at email time).
            is_region_suppressed = finding.finding_id in self._region_suppressed_ids
            is_suppressed = hospital_enabled and not is_region_suppressed and finding.notification_status == "Hospital Suppressed"
            is_inconclusive = hospital_enabled and not is_suppressed and not is_region_suppressed and bool(finding.suppression_reason)
            if is_region_suppressed:
                row_tag_name = "region_suppressed"
            elif is_suppressed:
                row_tag_name = "suppressed"
            elif is_inconclusive:
                row_tag_name = "suppression_inconclusive"
            else:
                row_tag_name = None

            # The one place these values are computed -- both the Treeview's
            # own `values=` tuple below and the exported row (Milestone 55)
            # read from this same dict, so they can never drift apart.
            # "_row_tag" is not in COLUMNS, so it's invisible to the
            # exported spreadsheet itself -- it only drives _findings_row_style.
            display_row = {
                "employee_name": finding.employee_name,
                "employee_code": finding.employee_code,
                "division": finding.division or "",
                "visit_date": finding.visit_date,
                "rule_name": finding.rule_name,
                "notification_status": self._display_status(finding),
                "status": finding.status,
                "message": finding.message,
                "_row_tag": row_tag_name,
            }
            self._current_display_rows.append(display_row)

            tree.insert(
                "",
                "end",
                iid=str(finding.finding_id),
                tags=(row_tag_name,) if row_tag_name else (),
                values=tuple(display_row[col] for col in COLUMNS),
            )
        tree.pack(fill="both", expand=True)
        tree.bind("<<TreeviewSelect>>", lambda event, t=tree: self._on_row_selected(t))

    # --- HR-Based tab ------------------------------------------------------

    def _on_hr_status_filter_changed(self, value: str) -> None:
        self._hr_status_filter = value
        self._render_hr_table()

    def _on_hr_export_clicked(self) -> None:
        """Exports the exact rows `_render_hr_table()` just displayed (post
        status filter + search), same contract as the Location tab's own
        Export."""
        suffix = "" if self._hr_status_filter == "All" else self._hr_status_filter
        export_rows_with_ui(
            self,
            rows=self._hr_display_rows,
            columns=HR_COLUMNS,
            headings=HR_HEADINGS,
            suggested_filename=default_export_filename("Low Working Hours", suffix=suffix),
            sheet_title="Low Working Hours",
        )

    def _render_hr_table(self) -> None:
        for widget in self.hr_table_container.winfo_children():
            widget.destroy()
        self._hr_display_rows = []

        query = self.hr_search_entry.get().strip().lower()
        # Region-suppressed HR findings STAY VISIBLE here, exactly like the
        # Location tab: tinted and shown as "Suppressed - Region Rule", not
        # actionable and never emailed (build_email_batch withholds them), but
        # never hidden or removed. The finding itself is unchanged.
        findings = [f for f in self._findings_by_id.values() if f.rule_name in HR_RULE_NAMES]

        if self._hr_status_filter != "All":
            findings = [f for f in findings if f.status == self._hr_status_filter]

        if query:
            findings = [
                f for f in findings
                if query in f.employee_name.lower() or query in f.employee_code.lower()
            ]

        findings.sort(key=lambda f: (f.visit_date is None, f.visit_date), reverse=True)

        if not findings:
            message = (
                "No active session file — import a workbook on the Operations page."
                if get_active_import_id() is None
                else "No low-working-hours findings match the current filter."
            )
            EmptyState(self.hr_table_container, message).pack(fill="both", expand=True)
            return

        tree = styled_treeview(self.hr_table_container, HR_COLUMNS, HR_HEADINGS, HR_WIDTHS, height=14)
        # Same purple region-suppressed tint the Location tab uses.
        tree.tag_configure("region_suppressed", background=Color.PRIMARY_SOFT)
        for finding in findings:
            parsed = _parse_hours_fields(finding.message)
            is_region_supp = finding.finding_id in self._region_suppressed_ids
            display_row = {
                "employee": f"{finding.employee_name} ({finding.employee_code})",
                "visit_date": finding.visit_date,
                "status": hr_status_text(finding, self._region_suppressed_ids),
                **parsed,
            }
            self._hr_display_rows.append(display_row)
            tree.insert(
                "",
                "end",
                iid=str(finding.finding_id),
                tags=("region_suppressed",) if is_region_supp else (),
                values=tuple(display_row[col] for col in HR_COLUMNS),
            )
        tree.pack(fill="both", expand=True)
        tree.bind("<<TreeviewSelect>>", lambda event, t=tree: self._on_row_selected(t))

    # --- Shared detail panel (both tabs) -----------------------------------

    def _on_row_selected(self, tree) -> None:
        selection = tree.selection()
        if not selection:
            self._render_detail(None)
            return
        finding = self._findings_by_id.get(int(selection[0]))
        self._render_detail(finding)

    def _render_detail(self, finding) -> None:
        for widget in self.detail_container.winfo_children():
            widget.destroy()

        ctk.CTkLabel(
            self.detail_container, text="Finding Detail", font=Font.H3, text_color=Color.TEXT_PRIMARY, anchor="w"
        ).pack(anchor="w", pady=(0, Spacing.MD))

        if finding is None:
            EmptyState(self.detail_container, "Select a finding to see details.").pack(fill="both", expand=True)
            return

        def field(label, value):
            ctk.CTkLabel(
                self.detail_container, text=label, font=Font.SMALL_BOLD, text_color=Color.TEXT_MUTED, anchor="w"
            ).pack(anchor="w", pady=(Spacing.SM, 0))
            ctk.CTkLabel(
                self.detail_container,
                text=str(value),
                font=Font.BODY,
                text_color=Color.TEXT_PRIMARY,
                anchor="w",
                wraplength=270,
                justify="left",
            ).pack(anchor="w")

        field("Employee", f"{finding.employee_name} ({finding.employee_code})")
        if finding.division:
            field("Division", finding.division)
        field("Visit Date", finding.visit_date)
        field("Rule", finding.rule_name)
        field("Message", finding.message)

        notification_display = self._display_status(finding)
        ctk.CTkLabel(
            self.detail_container, text="Status", font=Font.SMALL_BOLD, text_color=Color.TEXT_MUTED, anchor="w"
        ).pack(anchor="w", pady=(Spacing.SM, 4))
        StatusBadge(
            self.detail_container, notification_display, NOTIFICATION_BADGE_KIND.get(notification_display, "neutral")
        ).pack(anchor="w")

        hospital_enabled = is_feature_enabled("hospital_suppression")
        if finding.finding_id in self._region_suppressed_ids:
            # Region Suppression (app/region_suppression.py) is decided by the
            # canonical live rule, so this block shows the moment the finding
            # exists -- not only after the email pipeline stamps the status.
            # It's a separate, simpler block (just the reason, no
            # facility/coordinate fields) so it never reads as Hospital
            # Suppression below.
            ctk.CTkLabel(
                self.detail_container,
                text="Region Suppression",
                font=Font.SMALL_BOLD,
                text_color=Color.TEXT_MUTED,
                anchor="w",
            ).pack(anchor="w", pady=(Spacing.MD, 0))
            field("Reason", finding.suppression_reason or "This employee's region is subject to the Region Suppression Rule.")
        elif hospital_enabled and finding.notification_status == "Hospital Suppressed":
            ctk.CTkLabel(
                self.detail_container,
                text="Suppression Details",
                font=Font.SMALL_BOLD,
                text_color=Color.TEXT_MUTED,
                anchor="w",
            ).pack(anchor="w", pady=(Spacing.MD, 0))
            if finding.hospital_name:
                field("Hospital / Medical Facility", finding.hospital_name)
            if finding.hospital_distance_meters is not None:
                field("Distance From Cluster", f"{finding.hospital_distance_meters} meters")
            if finding.hospital_lat is not None and finding.hospital_lon is not None:
                field("Hospital Coordinates", f"{finding.hospital_lat}, {finding.hospital_lon}")
            if finding.cluster_lat is not None and finding.cluster_lon is not None:
                field("Employee Cluster Coordinates", f"{finding.cluster_lat}, {finding.cluster_lon}")
            if finding.suppression_reason:
                field("Reason", finding.suppression_reason)
        elif hospital_enabled and finding.suppression_reason:
            # Not suppressed, but the hospital check itself couldn't be
            # completed (lookup failure, or the batch's circuit breaker
            # skipped it) — see app.findings_service.note_suppression_check_issue.
            # Surfaced distinctly so this never reads the same as a finding
            # that was genuinely checked and cleared.
            ctk.CTkLabel(
                self.detail_container,
                text="Suppression Check Inconclusive",
                font=Font.SMALL_BOLD,
                text_color=Color.WARNING,
                anchor="w",
            ).pack(anchor="w", pady=(Spacing.MD, 0))
            field("Reason", finding.suppression_reason)

        ctk.CTkLabel(
            self.detail_container, text="Review Status", font=Font.SMALL_BOLD, text_color=Color.TEXT_MUTED, anchor="w"
        ).pack(anchor="w", pady=(Spacing.SM, 4))
        StatusBadge(
            self.detail_container, finding.status, STATUS_BADGE_KIND.get(finding.status, "neutral")
        ).pack(anchor="w")

        action_row = ctk.CTkFrame(self.detail_container, fg_color="transparent")
        action_row.pack(fill="x", pady=(Spacing.LG, 0))

        SecondaryButton(
            action_row, text="Mark Reviewed", command=lambda: self._on_set_status(finding.finding_id, "Reviewed")
        ).pack(fill="x", pady=(0, Spacing.SM))
        SecondaryButton(
            action_row, text="Mark Ignored", command=lambda: self._on_set_status(finding.finding_id, "Ignored")
        ).pack(fill="x", pady=(0, Spacing.SM))
        SecondaryButton(
            action_row, text="Reset to Open", command=lambda: self._on_set_status(finding.finding_id, "Open")
        ).pack(fill="x")

    def _on_set_status(self, finding_id: int, status: str) -> None:
        set_status(finding_id, status)
        self._load_findings(force=True)  # the reviewer's own action always refreshes now
        self._render_detail(self._findings_by_id.get(finding_id))
        # Push to the cloud in the background -- a reviewer's status change
        # should reach another laptop without this click blocking on the
        # network (see app/findings_sync_service.py).
        threading.Thread(target=push_finding_status, args=(finding_id,), daemon=True).start()
